CREATE TABLE registration_token
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    token         VARCHAR(255) NOT NULL UNIQUE,
    used          BOOLEAN                                 NOT NULL,
    created_by_id BIGINT,
    CONSTRAINT pk_registrationtoken PRIMARY KEY (id)
);

CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255) NOT NULL,
    email    VARCHAR(255) NOT NULL UNIQUE ,
    password VARCHAR(255) NOT NULL,
    role     VARCHAR(255) NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE registration_token
    ADD CONSTRAINT FK_REGISTRATIONTOKEN_ON_CREATED_BY FOREIGN KEY (created_by_id) REFERENCES users (id);