spring.application.name=wasteio-api

# PostgreSQL Configuration
spring.datasource.url=${DB_URL}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
# MQTT Configuration
mqtt.broker.url=tcp://localhost:1883
mqtt.client.id=wasteio-backend
mqtt.topic.telemetry=waste/containers/+/telemetry
mqtt.topic.events=waste/containers/+/events

simulator.devices.path=../container-device-simulator/devices.json


# JWT Configuration TODO: (MOMENTALNO VO APP.PROPERTIES, ZA VO PROD DA SE SMENI VO ENVIRONMENT VARIABLE)
jwt.secret=q8v1D0vW9rN4m4G5cD6rJzYk1vP8aL0s2Hf7TnQxU9E=
jwt.expiration=86400000