server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    resolver __KUBE_DNS__ valid=30s ipv6=off;

    location ~ ^/(api|auth|admin)/ {
        set $backend http://wasteio-api.wasteio.svc.cluster.local:80;
        proxy_pass $backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_buffering off;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
